language: java
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  - echo "deb http://repos.mesosphere.io/ubuntu/ precise main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
  # Add repository key
  - sudo apt-get update -qq
  - sudo apt-get install mesos -y </dev/null
branches:
  only:
    - master
sudo: required
dist: trusty
env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5
  matrix:
    - TEST_DIR=simulator DEPS_CMD='lein with-profiles +test deps' ps aux | grep mesos
    # - TEST_DIR=scheduler DEPS_CMD='lein with-profiles +test deps' TEST_CMD='lein test :all'
    # - TEST_DIR=jobclient DEPS_CMD='mvn dependency:resolve' TEST_CMD='mvn test'

#before_script: (cd $TEST_DIR && $DEPS_CMD)
before_script:
  - sudo service zookeeper restart

script:
  - ps aux | grep zookeeper
  - ps aux | grep mesos
  - which mesos-master
  - which mesos-slave
  - which mesos-init-wrapper
  - "mesos-master --zk=zk://127.0.0.1:2181/mesos --quorum=1 --ip=127.0.0.1 --workdir=/tmp/mesos"
  - sleep 10 && ps aux | grep mesos

after_script:
  - "sudo service zookeeper-server stop"
