language: java
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  - echo "deb http://repos.mesosphere.io/ubuntu/ precise main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
  - sudo apt-get update -qq
  - sudo apt-get install mesos -y </dev/null
branches:
  only:
    - master
sudo: required
dist: trusty
env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5
  matrix:
    - TEST_DIR=simulator DEPS_CMD='lein with-profiles +test deps' ps aux | grep mesos
    # - TEST_DIR=scheduler DEPS_CMD='lein with-profiles +test deps' TEST_CMD='lein test :all'
    # - TEST_DIR=jobclient DEPS_CMD='mvn dependency:resolve' TEST_CMD='mvn test'

#before_script: (cd $TEST_DIR && $DEPS_CMD)
script:
  - ps aux | grep mesos
  - sudo ls -l /usr/local/sbin/ | grep mesos
  - which mesos-master
  - which mesos-slave
#  - cat /etc/default/mesos-master
#  - touch /etc/default/mesos-master
#  - cat /etc/default/mesos-slave
#  - service mesos-slave start
#  - service mesos-master start
  - sleep 10 && ps aux | grep mesos
  - which zookeeper
  - mesos-master
  - mesos-slave
